name: load-forecasts
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - notebook
  - panel
  - jupyter-panel-proxy
  - diskcache
  - requests
  - pyarrow
  - openpyxl
  - pip
  - pip:
    - git+https://github.com/holoviz/panel.git#egg=panel